version: '3.7'

services:

  mailing-service:
    build: docker
    container_name: 'mailing-service'
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www
      - ./mnt:/mnt
    working_dir: /var/www

  nginx-mailing:
    image: nginx
    container_name: 'nginx-mailing'
    working_dir: /app
    restart: always
    ports:
      - '7778:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres-mailing:
    image: postgres:16
    ports:
      - '35432:5432'
    container_name: 'postgres-mailing'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'mailing'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

  memcached-mailing:
    image: memcached:latest
    container_name: 'memcached-mailing'
    restart: always
    ports:
      - 11211:11211

  redis-mailing:
    container_name: 'redis-mailing'
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq-mailing:
    image: rabbitmq:3.7.5-management
    working_dir: /app
    hostname: rabbit-mq
    container_name: 'rabbit-mq-mailing'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  supervisor:
    build: docker
    container_name: 'supervisor'
    volumes:
      - ./:/var/www
      - ./docker/supervisord.conf:/etc/supervisor/supervisord.conf
    working_dir: /var/www
    command: [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]

volumes:
  dump:
  postgresql:
